version: '3.8'

services:
  web:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: php_app
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "4500:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./php:/var/www/html
    depends_on:
      - web
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: meubanco
    volumes:
      - db_data:/var/lib/mysql
      - ./db/banco.sql:/docker-entrypoint-initdb.d/banco.sql
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
